export const channelsData = [
    { id: 1, name: "dT-DJfLipdE" },
    { id: 2, name: "dT-DJfLipdE" },
    { id: 3, name: "dT-DJfLipdE" },
    { id: 4, name: "dT-DJfLipdE" },
    { id: 5, name: "dT-DJfLipdE" },
    { id: 6, name: "dT-DJfLipdE" },
    { id: 7, name: "dT-DJfLipdE" },
    { id: 8, name: "dT-DJfLipdE" },
    { id: 9, name: "dT-DJfLipdE" },
    { id: 10, name: "dT-DJfLipdE" },
    { id: 11, name: "dT-DJfLipdE" },
    { id: 12, name: "dT-DJfLipdE" },
    { id: 13, name: "dT-DJfLipdE" },
    { id: 14, name: "dT-DJfLipdE" },
    { id: 15, name: "dT-DJfLipdE" },
    { id: 16, name: "dT-DJfLipdE" },
 ];