import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import "./globals.css";

export const metadata = {
  title: "Multi Channel",
  description: "Generated by create blakfy app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <Theme
          appearance="dark"
          accentColor="orange"
          grayColor="mauve"
          radius="small"
        >
          {children}
        </Theme>
      </body>
    </html>
  );
}
