import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import RadixTheme from "@/utils/RadixTheme";

export const metadata = {
  title: "Multi Channel",
  description: "Generated by create blakfy app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <RadixTheme>{children}</RadixTheme>
      </body>
    </html>
  );
}
